app = "travel-gpt-sep2023"

 [build]
 
 [deploy]
  release_command = "sh ./release.sh"
 
 [env]
  PORT = "3000"
  USERNAME = "postgres"
  PASSWORD = "SpYu2JKcWtDn21Z"
  DATABASE = "misty-sun-2237"
  HOST = "misty-sun-2237.internal"
  DIALECT = "postgres"
  NODE_ENV = "production"
  
[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]