app = "travel-gpt-sep2023"

 [build]
 
 [deploy]
  release_command = "sh ./release.sh"
 
 [env]
  PORT = "3000"
  USERNAME = "postgres"
  PASSWORD = "FBh5hrcqDBGCTRE"
  DATABASE = "travel-gpt-sep2023-db"
  HOST = "travel-gpt-sep2023-db.internal"
  DIALECT = "postgres"
  NODE_ENV = "production"
  OPENAI_API_KEY = "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"
  UNSPLASH_ACCESS_KEY = "2B31FLNGGRSwRaNHHozxJs8FNVYcK4qqdT-i_NbeCWU"
  
[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]